# Generated by Django 4.0.2 on 2022-02-15 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rareuser',
            name='profile_image_url',
        ),
    ]
