# Generated by Django 4.0.2 on 2022-02-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0003_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post_subject',
            field=models.CharField(default='This is the subject', max_length=200, verbose_name='Comment Subject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=1000, verbose_name='Comment Content'),
        ),
    ]
